### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ghost** [ridalarry/AntiCheat#5]
[ERROR] Error occurred while enabling AntiCheat v1 (Is it up to date?)

java.lang.NullPointerException

at me.rida.anticheat.AntiCheat.onEnable(AntiCheat.java:232) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

**Comment by ekclifford** [comment]
Could you please let us know what plugins you have?  And tell us if the anti-cheat has ever successfully enabled itself before, and if it has, can you please send us the config.yml file. Also, I attempted to replicate this error by using paper spigot, but it successfully enabled the plugin.

**Comment by ghost** [comment]
Everything is okay, i've used a bad plugin.yml i'm retarded thanks for the fast response tho c:
